In [1]:
import numpy as np

In [2]:
x = np.load('./save_data/npy_files/X.npy')
y = np.load('./save_data/npy_files/y.npy')
facs = np.load('./save_data/npy_files/facs.npy')

In [4]:
facs.shape

(1307, 15)

In [10]:
facs[5]

array([ 0,  1,  2,  5, 25, 27,  0,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int32)

In [25]:
facs_result = []
facs_temp = []
for index,facs_i in enumerate(facs):
    facs_temp = facs_i
    if facs_i[0] == 0 and facs_i[1] != 0:
        facs_temp = facs_i[1:]
        facs_temp = np.append(facs_temp, 0)
    print facs_temp
    facs_result.append(facs_temp)
facs_result = np.array(facs_result)
print facs_result.shape

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 9  2  4 17  0  0  0  0  0  0  0  0  0  0  0]
[ 9  2  4 17  0  0  0  0  0  0  0  0  0  0  0]
[ 9  2  4 17  0  0  0  0  0  0  0  0  0  0  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 1  2  5 25 27  0  0  0  0  0  0  0  0  0  0]
[ 1  2  5 25 27  0  0  0  0  0  0  0  0  0  0]
[ 1  2  5 25 27  0  0  0  0  0  0  0  0  0  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 4  5  7 17 23 24  0  0  0  0  0  0  0  0  0]
[ 4  5  7 17 23 24  0  0  0  0  0  0  0  0  0]
[ 4  5  7 17 23 24  0  0  0  0  0  0  0  0  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 3  6 12 16 25  0  0  0  0  0  0  0  0  0  0]
[ 3  6 12 16 25  0  0  0  0  0  0  0  0  0  0]
[ 3  6 12 16 25  0  0  0  0  0  0  0  0  0  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 1  2 27 25  0  0  0  0  0  0  0  0  0  0  0]
[ 1  2 27 25  0  0  0  0  0  0  0  0  0  0  0]
[ 1  2 27 25  0  0  0  0  0  0  0  0  0  0  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 1  4 17 15  0  0  0  0  0  0  0  0  0  0  0]
[ 1  4 17 15  0  0  0  0  0  0  0  0  0  0  0]
[ 1  4 17

[ 1  4  5  7 17 23 24 31  0  0  0  0  0  0  0]
[ 1  4  5  7 17 23 24 31  0  0  0  0  0  0  0]
[ 1  4  5  7 17 23 24 31  0  0  0  0  0  0  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 1  2  5 25 27  0  0  0  0  0  0  0  0  0  0]
[ 1  2  5 25 27  0  0  0  0  0  0  0  0  0  0]
[ 1  2  5 25 27  0  0  0  0  0  0  0  0  0  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[25 12  6  7  0  0  0  0  0  0  0  0  0  0  0]
[25 12  6  7  0  0  0  0  0  0  0  0  0  0  0]
[25 12  6  7  0  0  0  0  0  0  0  0  0  0  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 1  2  5 25 27  0  0  0  0  0  0  0  0  0  0]
[ 1  2  5 25 27  0  0  0  0  0  0  0  0  0  0]
[ 1  2  5 25 27  0  0  0  0  0  0  0  0  0  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[ 1  2 17 15  0  0  0  0  0  0  0  0  0  0  0]
[ 1  2 17 15  0  0  0  0  0  0  0  0  0  0  0]
[ 1  2 17 15  0  0  0  0  0  0  0  0  0  0  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[25 12  6  0  0  0  0  0  0  0  0  0  0  0  0]
[25 12  6  0  0  0  0  0  0  0  0  0  0  0  0]
[25 12  6  0  0  0  0  0  0  0  0  0  0  

In [30]:
np.save('./save_data/npy_files/facs_label.npy', facs_result)

In [29]:
facs_result.shape

(1307, 15)