In [1]:
import numpy as np

In [3]:
x = np.load('./save_data2/npy_files/X.npy')
y = np.load('./save_data2/npy_files/y.npy')
facs = np.load('./save_data2/npy_files/facs.npy')

In [4]:
facs.shape

(1307, 15)

In [5]:
facs[5]

array([ 1,  2, 27,  5, 25,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int32)

In [6]:
maxlen = 0
for i in facs:
    length = 0
    for j in i:
        if j != 0:
            length += 1
            if maxlen < length:
                maxlen = length
                print(i,maxlen)

[ 9 17  0  0  0  0  0  0  0  0  0  0  0  0  0] 1
[ 9 17  0  0  0  0  0  0  0  0  0  0  0  0  0] 2
[ 1  2 27  5 25  0  0  0  0  0  0  0  0  0  0] 3
[ 1  2 27  5 25  0  0  0  0  0  0  0  0  0  0] 4
[ 1  2 27  5 25  0  0  0  0  0  0  0  0  0  0] 5
[ 4 39  7 17 23 24  0  0  0  0  0  0  0  0  0] 6
[ 4  7 10 43 17 23 24  0  0  0  0  0  0  0  0] 7
[ 1  4  5  6  7 39 20 25  0  0  0  0  0  0  0] 8
[ 4  6  7 10 43 17 18 23 24  0  0  0  0  0  0] 9
[ 1  4  7 10 11 14 20 21 25 39  0  0  0  0  0] 10


In [7]:
facs_result = []

for index,facs_i in enumerate(facs):
    facs_temp = []
    facs_temp.append(0)
    facs_temp += list(facs_i[:-1])
    print (facs_temp)
    facs_result.append(facs_temp)
facs_result = np.array(facs_result)
print (facs_result.shape)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 9, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 9, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 9, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 27, 5, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 27, 5, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 27, 5, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 24, 17, 23, 4, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 24, 17, 23, 4, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 24, 17, 23, 4, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 16, 25, 12, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 16, 25, 12, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 16, 25, 12, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 27, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 27, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 27, 25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[

In [8]:
np.save('./save_data/npy_files/facs_label.npy', facs_result)

In [29]:
facs_result.shape

(1307, 15)

In [1]:
import os
import keras
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from keras.utils import np_utils
from keras.models import Sequential, Model
from keras.layers.merge import concatenate
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import  Input, Dense, Conv2D, Dropout, Flatten, MaxPooling2D, LSTM
from keras.datasets import cifar10
from keras.callbacks import ModelCheckpoint
from keras.models import model_from_json
from keras import backend as K

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
def make_model():
    k = float(np.random.rand()*1+0.2)
    print ('## k = %.3f' % k)
    winit1 = k/np.sqrt(5*5*1)
    winit2 = k/np.sqrt(5*5*64)
    winit3 = k/np.sqrt(5*5*128)
    
    cnn_input = Input(shape=(1,96,96))
    conv1 = Conv2D(filters=64, kernel_size=5, padding='same',
                    data_format='channels_first',
                    use_bias=False, 
                    kernel_initializer=keras.initializers.RandomNormal(mean=0.0, stddev=winit1),
                    activation='relu')(cnn_input)
    maxpool1 = MaxPooling2D(pool_size=2, strides=(2,2))(conv1)
    
    conv2 = Conv2D(filters=128, kernel_size=5, padding='same',
                    data_format='channels_first',
                    use_bias=False,
                    kernel_initializer=keras.initializers.RandomNormal(mean=0.0, stddev=winit2),
                    activation='relu')(maxpool1)
    maxpool2 = MaxPooling2D(pool_size=2, strides=(2,2))(conv2)
    
    conv3 = Conv2D(filters=256, kernel_size=5, padding='same',
                    data_format='channels_first',
                    use_bias=False,
                    kernel_initializer=keras.initializers.RandomNormal(mean=0.0, stddev=winit3),
                    activation='relu')(maxpool2)
    maxpool3 = MaxPooling2D(pool_size=12, strides=(12,12))(conv3)
    flatten = Flatten()(maxpool3)

    winitD1 = k/np.sqrt(4032)
    winitD2 = k/np.sqrt(300)
    dropout = Dropout(0.5)(flatten)
    dense1 = Dense(300, activation='relu',
                    kernel_initializer=keras.initializers.RandomNormal(mean=0.0, stddev=0.05),
                    bias_initializer='Ones')(dropout)

    cnn_output = Dense(8, activation='softmax',
    kernel_initializer=keras.initializers.RandomNormal(mean=0.0, stddev=winitD2),
    bias_initializer='Zeros')(dense1)

    cnn_model = Model(inputs=cnn_input, outputs=cnn_output)
    print(cnn_model.summary())
    
    # compile the model
    sgd = keras.optimizers.SGD(lr=0.01, decay=1e-5, momentum=0.9)
    cnn_model.compile(loss='categorical_crossentropy', optimizer=sgd,
             metrics=['accuracy'])
    
    # LSTM Model
    rnn_input = Input(shape=(15, 64))
    lstm1 = LSTM(250, return_sequences=True)(rnn_input)
    feature_and_class = Input(shape=(15,4040,))
    merge = concatenate([lstm1, feature_and_class])
    lstm2 = LSTM(250, return_sequences=True)(merge)
    rnn_output = Dense(64, activation='softmax')(lstm2)
    
    rnn_model = Model(inputs=[rnn_input, feature_and_class], outputs=rnn_output)
    print(rnn_model.summary())
    rnn_model.compile(loss='categorical_crossentropy', optimizer=sgd,
             metrics=['accuracy'])
    
    return cnn_model, rnn_model

In [3]:
def make_cv_folds(X, y, folds, fold_num):
    X_train = []
    y_train = []
    X_valid = []
    y_valid = []

    for index, fold in enumerate(folds):
        if fold == fold_num:
            X_valid.append(X[index])
            y_valid.append(y[index])
        else:
            X_train.append(X[index])
            y_train.append(y[index])
    X_train = np.array(X_train)
    y_train = np.array(y_train)
    X_valid = np.array(X_valid)
    y_valid = np.array(y_valid)


    return X_train, y_train, X_valid, y_valid

In [4]:
def load_data(dataset_path='./npy_files'):
    X = np.load(os.path.join(dataset_path,'X.npy'))
    y = np.load(os.path.join(dataset_path,'y.npy'))
    folds = np.load(os.path.join(dataset_path,'folds.npy'))
    
    # rescale [0,255] -> [0,2]    
    X = X.astype('float32')/255*2

    # one-hot encode the labels
    num_classes = len(np.unique(y))
    y = keras.utils.to_categorical(y, num_classes)
    
    return X, y

In [5]:
def load_cnn_model(model_path='./result/'):
    with open(os.path.join(model_path, 'model_architecture.json'), 'r') as f:
        model = model_from_json(f.read())

    model.load_weights(os.path.join(model_path, 'weights-42-0.90.hdf5'))
    
    return model

In [6]:
X, y = load_data('./save_data/npy_files/')
cnn_model = load_cnn_model('./result/test/')

In [7]:
inp = cnn_model.input                                           # input placeholder
outputs = cnn_model.layers[6].output          # all layer outputs
functor = K.function([inp]+ [K.learning_phase()], [outputs] ) # evaluation function

# Testing

layer_outs = functor([X, 1.])
print (layer_outs)

[array([[0.00011116, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)]


In [12]:
layer_outs[0].shape

(1307, 4032)

In [13]:
y_prob = cnn_model.predict(X)
y_classes = y_prob.argmax(axis=-1)

In [15]:
np.unique(y_classes)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
y_class_category = []
for inst in y_classes:
    temp = np.zeros(8)
    temp[inst] = 1
    y_class_category.append(temp)
y_class_np = np.array(y_class_category)

In [18]:
y_class_np.shape

(1307, 8)

In [22]:
a = [1]
b = [a] * 15

In [23]:
b

[[1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1]]

In [26]:
feature_time = []
for inst in layer_outs[0]:
    temp = [list(inst)] * 15
    feature_time.append(temp)
feature_time_np = np.array(feature_time)

In [30]:
class_time = []
for inst in y_class_np:
    temp = [list(inst)] * 15
    class_time.append(temp)
class_time_np = np.array(class_time)

In [27]:
feature_time_np.shape

(1307, 15, 4032)

In [31]:
class_time_np.shape

(1307, 15, 8)

In [33]:
feature_class = np.concatenate([feature_time_np, class_time_np],axis=2)

In [34]:
feature_class.shape

(1307, 15, 4040)

In [35]:
np.save('./save_data/npy_files/feature_class.npy', feature_class)