In [1]:
import numpy as np

In [2]:
x = np.load('./save_data/npy_files/X.npy')
y = np.load('./save_data/npy_files/y.npy')
facs = np.load('./save_data/npy_files/facs.npy')

In [3]:
facs.shape

(1307, 10)

In [4]:
facs[5]

array([ 1,  2, 27,  5, 25,  0,  0,  0,  0,  0], dtype=int32)

In [25]:
maxlen = 0
for i in facs:
    length = 0
    for j in i:
        if j != 0:
            length += 1
            if maxlen < length:
                maxlen = length
                print(i,maxlen)

[ 9 17  0  0  0  0  0  0  0  0] 1
[ 9 17  0  0  0  0  0  0  0  0] 2
[ 1  2 27  5 25  0  0  0  0  0] 3
[ 1  2 27  5 25  0  0  0  0  0] 4
[ 1  2 27  5 25  0  0  0  0  0] 5
[ 4 39  7 17 23 24  0  0  0  0] 6
[ 4  7 10 43 17 23 24  0  0  0] 7
[ 1  4  5  6  7 39 20 25  0  0] 8
[ 4  6  7 10 43 17 18 23 24  0] 9
[ 1  4  7 10 11 14 20 21 25 39] 10


In [17]:
facs_result = []

for index,facs_i in enumerate(facs):
    facs_temp = []
    facs_temp.append(0)
    facs_temp += list(facs_i[:-1])
    print (facs_temp)
    facs_result.append(facs_temp)
facs_result = np.array(facs_result)
print (facs_result.shape)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 9, 17, 0, 0, 0, 0, 0, 0, 0]
[0, 9, 17, 0, 0, 0, 0, 0, 0, 0]
[0, 9, 17, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 27, 5, 25, 0, 0, 0, 0]
[0, 1, 2, 27, 5, 25, 0, 0, 0, 0]
[0, 1, 2, 27, 5, 25, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 24, 17, 23, 4, 7, 0, 0, 0, 0]
[0, 24, 17, 23, 4, 7, 0, 0, 0, 0]
[0, 24, 17, 23, 4, 7, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 16, 25, 12, 6, 0, 0, 0, 0, 0]
[0, 16, 25, 12, 6, 0, 0, 0, 0, 0]
[0, 16, 25, 12, 6, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 27, 25, 0, 0, 0, 0, 0]
[0, 1, 2, 27, 25, 0, 0, 0, 0, 0]
[0, 1, 2, 27, 25, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 4, 17, 15, 0, 0, 0, 0, 0]
[0, 1, 4, 17, 15, 0, 0, 0, 0, 0]
[0, 1, 4, 17, 15, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 4, 25, 20, 7, 0, 0, 0, 0]
[0, 1, 4, 25, 20, 7, 0, 0, 0, 0]
[0, 1, 4, 25, 20, 7, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 4, 39, 7, 17, 23, 24, 0, 0, 0]
[0, 4, 39, 7, 17, 23,

In [30]:
np.save('./save_data/npy_files/facs_label.npy', facs_result)

In [29]:
facs_result.shape

(1307, 15)